# SPDX-FileCopyrightText: 2022 Matthew Macdonald-Wallace <matt@doics.co>
#
# SPDX-License-Identifier: MIT-Modern-Variant

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-grafana-oteldemostack
  description: |
    Terraform code to create a Grafana Cloud Stack and associated dashboards
  annotations:
    github.com/project-slug: proffalken/terraform-grafana-oteldemostack
spec:
  type: library
  owner: Proffalken
  lifecycle: development
